# アプリ設定
spring.application.name=todoapp
server.port=8081
spring.thymeleaf.cache=false

# PostgreSQLデータベース設定
spring.datasource.url=jdbc:postgresql://dpg-d4eoe6rgk3sc73bs7fq0-a:5432/todoapp_mik
spring.datasource.username=todoapp_mik_user
spring.datasource.password=VM0Pboo3jJzIlSIdC1Dd2i4KFoLowdzT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# Weather API
weather.api.key=ae8bd2aceab823c18826907302109c1a

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
